import { GoogleGenAI, Type } from "@google/genai";
import { dailyTaskGenerationSystemPrompt } from "@/lib/ai-prompts";
import { getOptionalEnv } from "@/lib/env";
import {
  generateContextAwareFallbackStack,
  normalizeAiTasks
} from "@/lib/task-engine";
import type { AiDailyStackResponse } from "@/lib/ai/schemas";

const geminiTaskSchema = {
  type: Type.OBJECT,
  required: ["tasks"],
  properties: {
    tasks: {
      type: Type.ARRAY,
      minItems: 5,
      maxItems: 5,
      items: {
        type: Type.OBJECT,
        required: [
          "task_type",
          "title",
          "reason",
          "suggested_action",
          "impact_score",
          "urgency_score",
          "confidence_score",
          "estimated_time_minutes",
          "requires_approval",
          "source_platform",
          "related_record_id"
        ],
        properties: {
          task_type: {
            type: Type.STRING,
            enum: [
              "wasted_spend",
              "negative_keyword_review",
              "review_response",
              "review_request",
              "google_business_post",
              "photo_upload",
              "meta_post",
              "lead_follow_up",
              "weekly_report",
              "seo_cleanup"
            ]
          },
          title: { type: Type.STRING },
          reason: { type: Type.STRING },
          suggested_action: { type: Type.STRING },
          impact_score: { type: Type.NUMBER },
          urgency_score: { type: Type.NUMBER },
          confidence_score: { type: Type.NUMBER },
          estimated_time_minutes: { type: Type.NUMBER },
          requires_approval: { type: Type.BOOLEAN },
          source_platform: {
            type: Type.STRING,
            enum: [
              "google_business",
              "google_ads",
              "ga4",
              "search_console",
              "meta",
              "facebook",
              "instagram",
              "manual",
              "ai"
            ]
          },
          related_record_id: { type: Type.STRING }
        }
      }
    }
  }
};

export async function generateDailyStackWithGemini(input: unknown) {
  const apiKey = getOptionalEnv("GEMINI_API_KEY");
  const model = getOptionalEnv("GEMINI_MODEL") ?? "gemini-2.5-flash";

  if (!apiKey) {
    return {
      mode: "local_fallback",
      tasks: generateContextAwareFallbackStack(input),
      note:
        "Gemini is not configured, so DreamGrowth ranked today's work with the local operator engine."
    };
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model,
      contents: [
        dailyTaskGenerationSystemPrompt,
        JSON.stringify(input)
      ].join("\n\nSignals:\n"),
      config: {
        responseMimeType: "application/json",
        responseSchema: geminiTaskSchema
      }
    });

    const parsed = JSON.parse(response.text ?? "{}") as AiDailyStackResponse;

    return {
      mode: "gemini",
      tasks: parsed.tasks
        ? normalizeAiTasks(parsed.tasks)
        : generateContextAwareFallbackStack(input),
      note: "Structured tasks generated by Gemini. External actions still require owner approval."
    };
  } catch (error) {
    return {
      mode: "local_fallback",
      tasks: generateContextAwareFallbackStack(input),
      note:
        error instanceof Error
          ? `Gemini is temporarily unavailable, so DreamGrowth used the local operator engine instead. ${error.message}`
          : "Gemini is temporarily unavailable, so DreamGrowth used the local operator engine instead."
    };
  }
}
