import OpenAI from "openai";
import { dailyTaskGenerationSystemPrompt } from "@/lib/ai-prompts";
import { dailyStackJsonSchema, type AiDailyStackResponse } from "@/lib/ai/schemas";
import { getOptionalEnv } from "@/lib/env";
import {
  generateDailyGrowthStack,
  mockGrowthSignals
} from "@/lib/task-engine";
import { generateDailyStackWithGemini } from "@/lib/ai/gemini";

export async function generateDailyStackWithOpenAI(input: unknown) {
  const provider = getOptionalEnv("AI_PROVIDER") ?? "gemini";

  if (provider === "gemini") {
    return generateDailyStackWithGemini(input);
  }

  const apiKey = getOptionalEnv("OPENAI_API_KEY");
  const model = getOptionalEnv("OPENAI_MODEL") ?? "gpt-4o";

  if (!apiKey) {
    return {
      mode: "local_fallback",
      tasks: generateDailyGrowthStack(mockGrowthSignals),
      note: "OPENAI_API_KEY is not configured, so DreamGrowth used the local scoring engine."
    };
  }

  try {
    const client = new OpenAI({ apiKey });
    const response = await client.responses.create({
      model,
      input: [
        {
          role: "system",
          content: dailyTaskGenerationSystemPrompt
        },
        {
          role: "user",
          content: JSON.stringify(input)
        }
      ],
      text: {
        format: {
          type: "json_schema",
          ...dailyStackJsonSchema
        }
      }
    });

    const parsed = JSON.parse(response.output_text) as AiDailyStackResponse;

    return {
      mode: "openai",
      tasks: parsed.tasks,
      note: "Structured tasks generated by OpenAI. External actions still require owner approval."
    };
  } catch (error) {
    return {
      mode: "local_fallback",
      tasks: generateDailyGrowthStack(mockGrowthSignals),
      note:
        error instanceof Error
          ? `OpenAI call failed, so DreamGrowth used the local scoring engine. ${error.message}`
          : "OpenAI call failed, so DreamGrowth used the local scoring engine."
    };
  }
}
